In [1]:
# To import various libraries

import math
import numpy as np
np.set_printoptions(precision=3, suppress=True)    # for compact output

In [2]:
# Construct the 8 X 8 covariance matrix R of a Markov-1 process.

R = np.zeros((8,8))
size,size = R.shape
ro = 0.91
for i in range (0,size):
    t = 1
    for j in range (0,size):
        if (i==j):
            R[i,j] = 1
        if (i<j):
            R[i,j] = ro**t
            t = t+1
            
for i in range (0,size):
    for j in range (0,size):
        R[j,i] = R[i,j]
        
print("\n\t\tCovarianve Matrix R\n\n",R)


		Covarianve Matrix R

 [[1.    0.91  0.828 0.754 0.686 0.624 0.568 0.517]
 [0.91  1.    0.91  0.828 0.754 0.686 0.624 0.568]
 [0.828 0.91  1.    0.91  0.828 0.754 0.686 0.624]
 [0.754 0.828 0.91  1.    0.91  0.828 0.754 0.686]
 [0.686 0.754 0.828 0.91  1.    0.91  0.828 0.754]
 [0.624 0.686 0.754 0.828 0.91  1.    0.91  0.828]
 [0.568 0.624 0.686 0.754 0.828 0.91  1.    0.91 ]
 [0.517 0.568 0.624 0.686 0.754 0.828 0.91  1.   ]]


In [3]:
# Construct the Walsh-Haddamard Transform matrix.

H=np.array([[1,1],[1,-1]])
H1=(1/math.sqrt(2))*H
print("\nMatrix H1 is :\n",H1)

H2 = np.kron(H1, H1)
print("\nKronecker product  of H1 and H1 is H2 :\n",H2)

H3 = np.kron(H2, H1)
print("\n\tKronecker product  of H2 and H1 is H3 :\n\n",H3)


Matrix H1 is :
 [[ 0.707  0.707]
 [ 0.707 -0.707]]

Kronecker product  of H1 and H1 is H2 :
 [[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]

	Kronecker product  of H2 and H1 is H3 :

 [[ 0.354  0.354  0.354  0.354  0.354  0.354  0.354  0.354]
 [ 0.354 -0.354  0.354 -0.354  0.354 -0.354  0.354 -0.354]
 [ 0.354  0.354 -0.354 -0.354  0.354  0.354 -0.354 -0.354]
 [ 0.354 -0.354 -0.354  0.354  0.354 -0.354 -0.354  0.354]
 [ 0.354  0.354  0.354  0.354 -0.354 -0.354 -0.354 -0.354]
 [ 0.354 -0.354  0.354 -0.354 -0.354  0.354 -0.354  0.354]
 [ 0.354  0.354 -0.354 -0.354 -0.354 -0.354  0.354  0.354]
 [ 0.354 -0.354 -0.354  0.354 -0.354  0.354  0.354 -0.354]]


In [4]:
# Construct the DCT type-2 matrix.

p=math.pi
N = 8
C = np.zeros((N,N))

for k in range (0,N):
    for n in range (0,N):
        if k==0:
            C[k,n] = math.sqrt(1/N)
        else:
            C[k,n] = (math.sqrt(2/N))*(math.cos((p*((2*n)+1)*k)/(2*N)))
            
print("\n\t\tDCT type2 matrix is C\n\n",C)


		DCT type2 matrix is C

 [[ 0.354  0.354  0.354  0.354  0.354  0.354  0.354  0.354]
 [ 0.49   0.416  0.278  0.098 -0.098 -0.278 -0.416 -0.49 ]
 [ 0.462  0.191 -0.191 -0.462 -0.462 -0.191  0.191  0.462]
 [ 0.416 -0.098 -0.49  -0.278  0.278  0.49   0.098 -0.416]
 [ 0.354 -0.354 -0.354  0.354  0.354 -0.354 -0.354  0.354]
 [ 0.278 -0.49   0.098  0.416 -0.416 -0.098  0.49  -0.278]
 [ 0.191 -0.462  0.462 -0.191 -0.191  0.462 -0.462  0.191]
 [ 0.098 -0.278  0.416 -0.49   0.49  -0.416  0.278 -0.098]]


In [5]:
# Construct the Hermitian of DCT type-2 matrix

C_h = np.zeros((N,N))
for i in range (0,N):
    C_h[:,i]=C[i,:]

print("\n\t\tHermition of DCT type-2 matrix\n\n",C_h)


		Hermition of DCT type-2 matrix

 [[ 0.354  0.49   0.462  0.416  0.354  0.278  0.191  0.098]
 [ 0.354  0.416  0.191 -0.098 -0.354 -0.49  -0.462 -0.278]
 [ 0.354  0.278 -0.191 -0.49  -0.354  0.098  0.462  0.416]
 [ 0.354  0.098 -0.462 -0.278  0.354  0.416 -0.191 -0.49 ]
 [ 0.354 -0.098 -0.462  0.278  0.354 -0.416 -0.191  0.49 ]
 [ 0.354 -0.278 -0.191  0.49  -0.354 -0.098  0.462 -0.416]
 [ 0.354 -0.416  0.191  0.098 -0.354  0.49  -0.462  0.278]
 [ 0.354 -0.49   0.462 -0.416  0.354 -0.278  0.191 -0.098]]


In [6]:
# Transform R using WHT and name the transform as `wht_R`
# wht_R = H3*R*H3

wht_R = np.dot(H3,(np.dot(R,H3)))

In [7]:
# Transform R DCT and name the transform `dct_R`.
# dct_R = C*R*C_h

dct_R = np.dot(C,(np.dot(R,C_h)))

In [8]:
# Enter the value of M. M should be less than 8

M=int(input("M is the number of coefficients we want to keep in.\n(maximum value of M is 8)\nEnter the value of M. :- ")) 

M is the number of coefficients we want to keep in.
(maximum value of M is 8)
Enter the value of M. :- 5


In [9]:
# Energy Packing Efficiency of Walsh-Haddamard Transform

s1 = 0
for i in range (0,M):
    s1 = s1 + wht_R[i,i]

s2 = 0
for j in range (0,N):
    s2 = s2 + wht_R[j,j]

epe_wht = s1/s2
print("Energy Packing Efficiency of Walsh-Haddamard Transform : ", epe_wht)

Energy Packing Efficiency of Walsh-Haddamard Transform :  0.9424071362893965


In [10]:
# Decorrelation Efficiency of Walsh-Haddamard Transform

s3 = 0
for i in range (0,N):
    for j in range (0,N):
        if i!=j:
            s3 = s3 + abs(wht_R[i,j])

s4 = 0
for i in range (0,N):
    for j in range (0,N):
        if i!=j:
            s4 = s4 + abs(R[i,j])

de_wht = 1-(s3/s4)
print("Decorrelation Efficiency of Walsh-Haddamard Transform : ", de_wht)

Decorrelation Efficiency of Walsh-Haddamard Transform :  0.9485667904674058


In [11]:
# Energy Packing Efficiency of DCT

s11 = 0
for i in range (0,M):
    s11 = s11 + dct_R[i,i]

s22 = 0
for j in range (0,N):
    s22 = s22 + dct_R[j,j]

epe_dct = s11/s22
print("Energy Packing Efficiency of DCT : ", epe_dct)

Energy Packing Efficiency of DCT :  0.9785067153152943


In [12]:
# Decorrelation Efficiency of DCT

s33 = 0
for i in range (0,N):
    for j in range (0,N):
        if i!=j:
            s33 = s33 + abs(dct_R[i,j])

s44 = 0
for i in range (0,N):
    for j in range (0,N):
        if i!=j:
            s44 = s44 + abs(R[i,j])

de_dct = 1-(s33/s44)
print("Decorrelation Efficiency of DCT : ", de_dct)

Decorrelation Efficiency of DCT :  0.9804711989227338


In [13]:
# finding eigenvalues and eigenvectors of R

w, v = np.linalg.eig(R)
print("\n\t\t\tEigen-values\n",w)
print("\n\t\t\tEigen-vectors\n",v)


			Eigen-values
 [6.358 0.931 0.298 0.148 0.093 0.068 0.055 0.049]

			Eigen-vectors
 [[-0.327 -0.473  0.469  0.428  0.366  0.288  0.198 -0.101]
 [-0.349 -0.424  0.218 -0.076 -0.341 -0.486 -0.463  0.279]
 [-0.365 -0.292 -0.169 -0.483 -0.358  0.091  0.459 -0.415]
 [-0.372 -0.104 -0.451 -0.279  0.349  0.415 -0.19   0.489]
 [-0.372  0.104 -0.451  0.279  0.349 -0.415 -0.19  -0.489]
 [-0.365  0.292 -0.169  0.483 -0.358 -0.091  0.459  0.415]
 [-0.349  0.424  0.218  0.076 -0.341  0.486 -0.463 -0.279]
 [-0.327  0.473  0.469 -0.428  0.366 -0.288  0.198  0.101]]


In [14]:
#  Each column is the Eigen vector of R
print("\n\t\t\tEigen-vectors of R(Columns)\n\n",v)


			Eigen-vectors of R(Columns)

 [[-0.327 -0.473  0.469  0.428  0.366  0.288  0.198 -0.101]
 [-0.349 -0.424  0.218 -0.076 -0.341 -0.486 -0.463  0.279]
 [-0.365 -0.292 -0.169 -0.483 -0.358  0.091  0.459 -0.415]
 [-0.372 -0.104 -0.451 -0.279  0.349  0.415 -0.19   0.489]
 [-0.372  0.104 -0.451  0.279  0.349 -0.415 -0.19  -0.489]
 [-0.365  0.292 -0.169  0.483 -0.358 -0.091  0.459  0.415]
 [-0.349  0.424  0.218  0.076 -0.341  0.486 -0.463 -0.279]
 [-0.327  0.473  0.469 -0.428  0.366 -0.288  0.198  0.101]]


In [15]:
#  Each column is the DCT-2 basis vector

print("\n\t\t\tDCT-Basis(Columns)\n\n",C_h)


			DCT-Basis(Columns)

 [[ 0.354  0.49   0.462  0.416  0.354  0.278  0.191  0.098]
 [ 0.354  0.416  0.191 -0.098 -0.354 -0.49  -0.462 -0.278]
 [ 0.354  0.278 -0.191 -0.49  -0.354  0.098  0.462  0.416]
 [ 0.354  0.098 -0.462 -0.278  0.354  0.416 -0.191 -0.49 ]
 [ 0.354 -0.098 -0.462  0.278  0.354 -0.416 -0.191  0.49 ]
 [ 0.354 -0.278 -0.191  0.49  -0.354 -0.098  0.462 -0.416]
 [ 0.354 -0.416  0.191  0.098 -0.354  0.49  -0.462  0.278]
 [ 0.354 -0.49   0.462 -0.416  0.354 -0.278  0.191 -0.098]]


In [16]:
#  Difference between magnitude of Eigen-vectors of R(Columns) and magnitude of DCT-2 basis vector(Columns)

Error_diff = abs(v)-abs(C_h)
print("\n\t\tError_diff\n\n",abs(Error_diff))


		Error_diff

 [[0.027 0.017 0.007 0.012 0.012 0.01  0.007 0.004]
 [0.004 0.008 0.027 0.022 0.012 0.004 0.001 0.002]
 [0.011 0.015 0.022 0.007 0.004 0.006 0.003 0.   ]
 [0.019 0.007 0.011 0.001 0.004 0.001 0.002 0.001]
 [0.019 0.007 0.011 0.001 0.004 0.001 0.002 0.001]
 [0.011 0.015 0.022 0.007 0.004 0.006 0.003 0.   ]
 [0.004 0.008 0.027 0.022 0.012 0.004 0.001 0.002]
 [0.027 0.017 0.007 0.012 0.012 0.01  0.007 0.004]]
