In [1]:
# To import various libraries

import math
import numpy as np
np.set_printoptions(precision=3, suppress=True)    # for compact output

In [2]:
# Construct the 8 X 8 covariance matrix R of a Markov-1 process.

R = np.zeros((8,8))
size,size = R.shape
ro = 0.91
for i in range (0,size):
    t = 1
    for j in range (0,size):
        if (i==j):
            R[i,j] = 1
        if (i<j):
            R[i,j] = ro**t
            t = t+1
            
for i in range (0,size):
    for j in range (0,size):
        R[j,i] = R[i,j]
        
print("\n\t\tCovarianve Matrix R\n\n",R)


		Covarianve Matrix R

 [[1.    0.91  0.828 0.754 0.686 0.624 0.568 0.517]
 [0.91  1.    0.91  0.828 0.754 0.686 0.624 0.568]
 [0.828 0.91  1.    0.91  0.828 0.754 0.686 0.624]
 [0.754 0.828 0.91  1.    0.91  0.828 0.754 0.686]
 [0.686 0.754 0.828 0.91  1.    0.91  0.828 0.754]
 [0.624 0.686 0.754 0.828 0.91  1.    0.91  0.828]
 [0.568 0.624 0.686 0.754 0.828 0.91  1.    0.91 ]
 [0.517 0.568 0.624 0.686 0.754 0.828 0.91  1.   ]]


In [3]:
# Calculating the inverse of the matrix R

R_inverse = np.linalg.inv(R)
print("\n\t\t\tR_inverse\n\n",R_inverse)


			R_inverse

 [[ 5.817 -5.294 -0.    -0.     0.    -0.     0.    -0.   ]
 [-5.294 10.635 -5.294 -0.    -0.     0.    -0.     0.   ]
 [-0.    -5.294 10.635 -5.294 -0.     0.    -0.    -0.   ]
 [-0.    -0.    -5.294 10.635 -5.294  0.     0.     0.   ]
 [-0.     0.    -0.    -5.294 10.635 -5.294 -0.    -0.   ]
 [-0.     0.     0.    -0.    -5.294 10.635 -5.294 -0.   ]
 [ 0.    -0.    -0.     0.    -0.    -5.294 10.635 -5.294]
 [-0.     0.     0.    -0.     0.    -0.    -5.294  5.817]]


In [4]:
# Calculating matrix (BETA_SQUARE * R_INVERSE) i.e D


beta_sq = (1-(ro**2))/(1+(ro**2))
D = beta_sq*R_inverse
print("\n\t\tBETA_SQUARE * R_INVERSE\n\n", D)


		BETA_SQUARE * R_INVERSE

 [[ 0.547 -0.498 -0.    -0.     0.    -0.     0.    -0.   ]
 [-0.498  1.    -0.498 -0.    -0.     0.    -0.     0.   ]
 [-0.    -0.498  1.    -0.498 -0.     0.    -0.    -0.   ]
 [-0.    -0.    -0.498  1.    -0.498  0.     0.     0.   ]
 [-0.     0.    -0.    -0.498  1.    -0.498 -0.    -0.   ]
 [-0.     0.     0.    -0.    -0.498  1.    -0.498 -0.   ]
 [ 0.    -0.    -0.     0.    -0.    -0.498  1.    -0.498]
 [-0.     0.     0.    -0.     0.    -0.    -0.498  0.547]]


In [5]:
# Tridiagonal Matrix Q

alpha = ro/(1+(ro**2))
Q = np.zeros((8,8))
size,size = Q.shape
for i in range (1,size-1):
    t = 1
    for j in range (1,size-1):
        if (i==j):
            Q[i,j] = 1
            Q[i,j+1] = -alpha
            Q[i,j-1] = -alpha
        
Q[0,0] = 1-alpha
Q[0,1] = -alpha
Q[size-1,size-1] = 1-alpha
Q[size-1,size-2] = -alpha

print("\n\t\t\tQ\n\n",Q)


			Q

 [[ 0.502 -0.498  0.     0.     0.     0.     0.     0.   ]
 [-0.498  1.    -0.498  0.     0.     0.     0.     0.   ]
 [ 0.    -0.498  1.    -0.498  0.     0.     0.     0.   ]
 [ 0.     0.    -0.498  1.    -0.498  0.     0.     0.   ]
 [ 0.     0.     0.    -0.498  1.    -0.498  0.     0.   ]
 [ 0.     0.     0.     0.    -0.498  1.    -0.498  0.   ]
 [ 0.     0.     0.     0.     0.    -0.498  1.    -0.498]
 [ 0.     0.     0.     0.     0.     0.    -0.498  0.502]]


In [6]:
# Construct the DCT type-2 matrix.

p=math.pi
N = 8
C = np.zeros((N,N))

for k in range (0,N):
    for n in range (0,N):
        if k==0:
            C[k,n] = math.sqrt(1/N)
        else:
            C[k,n] = (math.sqrt(2/N))*(math.cos((p*((2*n)+1)*k)/(2*N)))
            
print(" \n\t\tDCT type-2 matrix is C\n\n",C)

 
		DCT type-2 matrix is C

 [[ 0.354  0.354  0.354  0.354  0.354  0.354  0.354  0.354]
 [ 0.49   0.416  0.278  0.098 -0.098 -0.278 -0.416 -0.49 ]
 [ 0.462  0.191 -0.191 -0.462 -0.462 -0.191  0.191  0.462]
 [ 0.416 -0.098 -0.49  -0.278  0.278  0.49   0.098 -0.416]
 [ 0.354 -0.354 -0.354  0.354  0.354 -0.354 -0.354  0.354]
 [ 0.278 -0.49   0.098  0.416 -0.416 -0.098  0.49  -0.278]
 [ 0.191 -0.462  0.462 -0.191 -0.191  0.462 -0.462  0.191]
 [ 0.098 -0.278  0.416 -0.49   0.49  -0.416  0.278 -0.098]]


In [7]:
# Construct the Hermitian of DCT type-2 matrix

C_h = np.zeros((N,N))
for i in range (0,N):
    C_h[:,i]=C[i,:]

print("\n\t\tHermition of DCT type-2 matrix\n\n",C_h)


		Hermition of DCT type-2 matrix

 [[ 0.354  0.49   0.462  0.416  0.354  0.278  0.191  0.098]
 [ 0.354  0.416  0.191 -0.098 -0.354 -0.49  -0.462 -0.278]
 [ 0.354  0.278 -0.191 -0.49  -0.354  0.098  0.462  0.416]
 [ 0.354  0.098 -0.462 -0.278  0.354  0.416 -0.191 -0.49 ]
 [ 0.354 -0.098 -0.462  0.278  0.354 -0.416 -0.191  0.49 ]
 [ 0.354 -0.278 -0.191  0.49  -0.354 -0.098  0.462 -0.416]
 [ 0.354 -0.416  0.191  0.098 -0.354  0.49  -0.462  0.278]
 [ 0.354 -0.49   0.462 -0.416  0.354 -0.278  0.191 -0.098]]


In [8]:
# Diagonalizing Tridiagonal Matrix Q using the DCT matrix

DQ = np.dot(C,(np.dot(Q,C_h)))
print("\n\tDiagonal Matrix after DIAGONALIZING Q\n\n",DQ)


	Diagonal Matrix after DIAGONALIZING Q

 [[ 0.004 -0.    -0.    -0.     0.    -0.    -0.    -0.   ]
 [ 0.     0.08  -0.     0.    -0.    -0.     0.    -0.   ]
 [-0.    -0.     0.296  0.    -0.     0.    -0.     0.   ]
 [ 0.     0.     0.     0.619  0.    -0.     0.    -0.   ]
 [ 0.    -0.    -0.     0.     1.     0.    -0.    -0.   ]
 [-0.    -0.     0.    -0.     0.     1.381  0.     0.   ]
 [-0.     0.    -0.     0.    -0.     0.     1.704 -0.   ]
 [ 0.    -0.     0.    -0.    -0.     0.    -0.     1.92 ]]


In [9]:
# Diagonalizing matrix (BETA_SQUARE * R_INVERSE) i.e D using the DCT matrix

DD = np.dot(C,(np.dot(D,C_h)))
print("\nDiagonal Matrix after DIAGONALIZING BETA_SQUARE*R_INVERSE i.e D:\n\n",DD)


Diagonal Matrix after DIAGONALIZING BETA_SQUARE*R_INVERSE i.e D:

 [[ 0.016  0.     0.015 -0.     0.011  0.     0.006  0.   ]
 [-0.     0.102 -0.     0.018 -0.     0.012  0.     0.004]
 [ 0.015 -0.     0.315  0.     0.015  0.     0.008  0.   ]
 [-0.     0.018 -0.     0.634  0.     0.01   0.     0.004]
 [ 0.011 -0.     0.015  0.     1.011  0.     0.006  0.   ]
 [ 0.     0.012  0.     0.01   0.     1.388  0.     0.002]
 [ 0.006  0.     0.008  0.     0.006  0.     1.707  0.   ]
 [-0.     0.004  0.     0.004  0.     0.002  0.     1.921]]
