In [1]:
# Importing various libraries

import math
import numpy as np
from PIL import Image
import scipy.io
mat = scipy.io.loadmat('imageFile.mat')
np.set_printoptions(precision=3, suppress=True)    # for compact output

In [2]:
# Loading g matrix

g = mat['g']
N,N = g.shape
print("\n\t\tg matrix\n\n",g)


		g matrix

 [[207 244 107 173  70 111 180 244]
 [230 246 233 193  11  97 192  86]
 [ 32  40 202 189  24 195  70 149]
 [232 247 244 100 209 202 173  57]
 [161 244 167 167 177  47 167 191]
 [ 24 123   9  43  80 124  41  65]
 [ 71 204 216 180 242 113  30 129]
 [139  36 238   8   8 164 127 178]]


In [3]:
# Construct the Hermitian of g matrix

g_h = np.zeros((N,N))
for i in range (0,N):
    g_h[:,i]=g[i,:]

print("\n\tHermition of g matrix\n\n",g_h)


	Hermition of g matrix

 [[207. 230.  32. 232. 161.  24.  71. 139.]
 [244. 246.  40. 247. 244. 123. 204.  36.]
 [107. 233. 202. 244. 167.   9. 216. 238.]
 [173. 193. 189. 100. 167.  43. 180.   8.]
 [ 70.  11.  24. 209. 177.  80. 242.   8.]
 [111.  97. 195. 202.  47. 124. 113. 164.]
 [180. 192.  70. 173. 167.  41.  30. 127.]
 [244.  86. 149.  57. 191.  65. 129. 178.]]


In [4]:
# Perform eigen-value decomposition

In [5]:
# Calculating matrix (g * g_hermitian) i.e E

E = np.dot(g,g_h)

In [6]:
# To find the eigenvalues and eigenvectors of matrix E (g * g_hermitian)

eigen_values_E, eigen_vectors_E = np.linalg.eig(E) 
print("\n\t\tEigen values\n\n",eigen_values_E)
print("\n\t\tEigenvectors\n\n",eigen_vectors_E)


		Eigen values

 [1367373.911   82768.139   66305.917   45917.807   26626.135   17617.098
    1033.995    2048.998]

		Eigenvectors

 [[ 0.408  0.045 -0.42  -0.472 -0.318 -0.179  0.543  0.069]
 [ 0.411 -0.093 -0.468  0.159  0.645 -0.084 -0.217  0.329]
 [ 0.271 -0.519  0.425 -0.351  0.325 -0.282  0.013 -0.41 ]
 [ 0.448  0.165  0.101  0.713 -0.125 -0.217  0.249 -0.36 ]
 [ 0.403  0.318 -0.115 -0.25  -0.113  0.442 -0.499 -0.451]
 [ 0.149  0.146  0.149 -0.078 -0.358 -0.655 -0.538  0.285]
 [ 0.36   0.342  0.614 -0.112  0.152  0.272  0.199  0.477]
 [ 0.277 -0.673  0.024  0.2   -0.445  0.369 -0.135  0.278]]


In [7]:
# Eigenvectors of matrix E (g * g_hermitian) are columns of matrix A

A = eigen_vectors_E
print("\n\t\t\tMatrix A\n\n" , A)


			Matrix A

 [[ 0.408  0.045 -0.42  -0.472 -0.318 -0.179  0.543  0.069]
 [ 0.411 -0.093 -0.468  0.159  0.645 -0.084 -0.217  0.329]
 [ 0.271 -0.519  0.425 -0.351  0.325 -0.282  0.013 -0.41 ]
 [ 0.448  0.165  0.101  0.713 -0.125 -0.217  0.249 -0.36 ]
 [ 0.403  0.318 -0.115 -0.25  -0.113  0.442 -0.499 -0.451]
 [ 0.149  0.146  0.149 -0.078 -0.358 -0.655 -0.538  0.285]
 [ 0.36   0.342  0.614 -0.112  0.152  0.272  0.199  0.477]
 [ 0.277 -0.673  0.024  0.2   -0.445  0.369 -0.135  0.278]]


In [8]:
# Calculating matrix (g_hermitian * g) i.e F

F = np.dot(g_h,g)

In [9]:
# To find the eigen values and eigen vectors of matrix F(g_hermitian * g)

eigen_values_F, eigen_vectors_F = np.linalg.eig(F)
print("\n\t\tEigen values\n\n",eigen_values_F)
print("\n\t\tEigenvectors\n\n",eigen_vectors_F)


		Eigen values

 [1367373.911   82768.139   66305.917   45917.807   26626.135   17617.098
    1033.995    2048.998]

		Eigenvectors

 [[ 0.363  0.017 -0.488  0.331 -0.086  0.079  0.712 -0.002]
 [ 0.446 -0.519 -0.23  -0.     0.04  -0.248 -0.342 -0.546]
 [ 0.441  0.394  0.299  0.33   0.345  0.497 -0.197 -0.217]
 [ 0.331 -0.083  0.098 -0.511  0.661 -0.185  0.239  0.29 ]
 [ 0.261 -0.589  0.533  0.156 -0.299  0.219  0.115  0.355]
 [ 0.301  0.385  0.379  0.174 -0.245 -0.723  0.067 -0.011]
 [ 0.315  0.117 -0.427  0.1   -0.109 -0.026 -0.511  0.649]
 [ 0.328  0.245 -0.01  -0.675 -0.522  0.282  0.039 -0.151]]


In [10]:
# Eigenvectors of matrix f (g_hermitian * g) are columns of matrix B

B = eigen_vectors_F
print("\n\t\t\tMatrix B\n\n" , B)


			Matrix B

 [[ 0.363  0.017 -0.488  0.331 -0.086  0.079  0.712 -0.002]
 [ 0.446 -0.519 -0.23  -0.     0.04  -0.248 -0.342 -0.546]
 [ 0.441  0.394  0.299  0.33   0.345  0.497 -0.197 -0.217]
 [ 0.331 -0.083  0.098 -0.511  0.661 -0.185  0.239  0.29 ]
 [ 0.261 -0.589  0.533  0.156 -0.299  0.219  0.115  0.355]
 [ 0.301  0.385  0.379  0.174 -0.245 -0.723  0.067 -0.011]
 [ 0.315  0.117 -0.427  0.1   -0.109 -0.026 -0.511  0.649]
 [ 0.328  0.245 -0.01  -0.675 -0.522  0.282  0.039 -0.151]]


In [11]:
# Construct the Hermitian of matrix B

B_h = np.zeros((N,N))
for i in range (0,N):
    B_h[:,i]=B[i,:]

print("\n\t\tHermition of B matrix\n\n",B_h)


		Hermition of B matrix

 [[ 0.363  0.446  0.441  0.331  0.261  0.301  0.315  0.328]
 [ 0.017 -0.519  0.394 -0.083 -0.589  0.385  0.117  0.245]
 [-0.488 -0.23   0.299  0.098  0.533  0.379 -0.427 -0.01 ]
 [ 0.331 -0.     0.33  -0.511  0.156  0.174  0.1   -0.675]
 [-0.086  0.04   0.345  0.661 -0.299 -0.245 -0.109 -0.522]
 [ 0.079 -0.248  0.497 -0.185  0.219 -0.723 -0.026  0.282]
 [ 0.712 -0.342 -0.197  0.239  0.115  0.067 -0.511  0.039]
 [-0.002 -0.546 -0.217  0.29   0.355 -0.011  0.649 -0.151]]


In [12]:
# Reconstruction of Image Matrix using the basis images

rank = np.linalg.matrix_rank(g)
sigma2=[]

s2=0
for k in range (0,rank):
    inter3 = np.dot(A[:,k].reshape((8,1)),B[:,k].reshape((1,8)))
    sig = 0
    
        
#     print(f"\nbasis_image_matrix{k}\n",inter3)
    
    # Inner product technique used to find singular values
    
    for i in range (0,8):
        for j in range (0,8):
            t = g[i,j]*inter3[i,j]
            sig = sig + t
            
    sigma2.append(sig)
            
    o2 = sig*inter3        
    s2 = s2 + o2
    
print("\nReconstruction of Image Matrix using the Basis Images (Method-1)\n\n",s2)


Reconstruction of Image Matrix using the Basis Images (Method-1)

 [[207. 244. 107. 173.  70. 111. 180. 244.]
 [230. 246. 233. 193.  11.  97. 192.  86.]
 [ 32.  40. 202. 189.  24. 195.  70. 149.]
 [232. 247. 244. 100. 209. 202. 173.  57.]
 [161. 244. 167. 167. 177.  47. 167. 191.]
 [ 24. 123.   9.  43.  80. 124.  41.  65.]
 [ 71. 204. 216. 180. 242. 113.  30. 129.]
 [139.  36. 238.   8.   8. 164. 127. 178.]]


In [13]:
# An array storing all the singular values

print(sigma2)

[1169.3476431872264, -287.69452437540156, 257.49935299162377, 214.2844068745785, 163.17516562327347, 132.7294165700074, 32.15579375532702, -45.265863793417765]


In [14]:
# SINGULAR VALUE MATRIX

SIGMA2 = np.zeros((8,8))
for i in range (0,8):
    for j in range (0,8):
        if i==j:
            SIGMA2[i,j]=sigma2[i]
            
print("\n\t\t\tSINGULAR VALUE MATRIX\n\n",SIGMA2)


			SINGULAR VALUE MATRIX

 [[1169.348    0.       0.       0.       0.       0.       0.       0.   ]
 [   0.    -287.695    0.       0.       0.       0.       0.       0.   ]
 [   0.       0.     257.499    0.       0.       0.       0.       0.   ]
 [   0.       0.       0.     214.284    0.       0.       0.       0.   ]
 [   0.       0.       0.       0.     163.175    0.       0.       0.   ]
 [   0.       0.       0.       0.       0.     132.729    0.       0.   ]
 [   0.       0.       0.       0.       0.       0.      32.156    0.   ]
 [   0.       0.       0.       0.       0.       0.       0.     -45.266]]


In [15]:
# Reconstruction of Image matrix using (Matrix A * Singular_value_matrix * matrix B Hermitian)

S2 = np.dot(A,(np.dot(SIGMA2,B_h)))
print("\nReconstruction of Image Matrix (Method-2)\n\n",S2)


Reconstruction of Image Matrix (Method-2)

 [[207. 244. 107. 173.  70. 111. 180. 244.]
 [230. 246. 233. 193.  11.  97. 192.  86.]
 [ 32.  40. 202. 189.  24. 195.  70. 149.]
 [232. 247. 244. 100. 209. 202. 173.  57.]
 [161. 244. 167. 167. 177.  47. 167. 191.]
 [ 24. 123.   9.  43.  80. 124.  41.  65.]
 [ 71. 204. 216. 180. 242. 113.  30. 129.]
 [139.  36. 238.   8.   8. 164. 127. 178.]]


In [16]:
# Q(4)

In [17]:
r=int(input("r is the number of singular values we want to keep in.\n(maximum value of r is 8)\nEnter the value of r. :- "))

r is the number of singular values we want to keep in.
(maximum value of r is 8)
Enter the value of r. :- 7


In [18]:
# Reconstruction of Image Matrix g_hat using the basis images

g_hat = 0
for k in range (0,r):
    inter4 = np.dot(A[:,k].reshape((8,1)),B[:,k].reshape((1,8)))
    sig = 0
    for i in range (0,8):
        for j in range (0,8):
            t = g[i,j]*inter4[i,j]
            sig = sig + t
    o4 = sig*inter4        
    g_hat = g_hat + o4
print("\n\tReconstruction of Image Matrix g_hat\n\n",g_hat)


	Reconstruction of Image Matrix g_hat

 [[206.992 242.295 106.324 173.906  71.106 110.967 182.026 243.529]
 [229.964 237.86  229.772 197.327  16.281  96.842 201.67   83.752]
 [ 32.045  50.152 206.026 183.604  17.414 195.197  57.94  151.804]
 [232.039 255.897 247.528  95.271 203.228 202.173 162.431  59.457]
 [161.05  255.158 171.425 161.069 169.761  47.216 153.745 194.082]
 [ 23.969 115.959   6.208  46.742  84.568 123.863  49.364  63.055]
 [ 70.948 192.207 211.323 186.269 249.651 112.771  44.009 125.743]
 [138.969  29.118 235.271  11.658  12.465 163.866 135.175 176.099]]


In [19]:
# Error matrix

E = g - g_hat
print("\n\t\tError matrix (Subtraction method(Method-1))\n\n",E)


		Error matrix (Subtraction method(Method-1))

 [[  0.008   1.705   0.676  -0.906  -1.106   0.033  -2.026   0.471]
 [  0.036   8.14    3.228  -4.327  -5.281   0.158  -9.67    2.248]
 [ -0.045 -10.152  -4.026   5.396   6.586  -0.197  12.06   -2.804]
 [ -0.039  -8.897  -3.528   4.729   5.772  -0.173  10.569  -2.457]
 [ -0.05  -11.158  -4.425   5.931   7.239  -0.216  13.255  -3.082]
 [  0.031   7.041   2.792  -3.742  -4.568   0.137  -8.364   1.945]
 [  0.052  11.793   4.677  -6.269  -7.651   0.229 -14.009   3.257]
 [  0.031   6.882   2.729  -3.658  -4.465   0.134  -8.175   1.901]]


In [20]:
# Error matrix

E2 = 0
for k in range (r,rank):
    inter5 = np.dot(A[:,k].reshape((8,1)),B[:,k].reshape((1,8)))
    sig = 0
    for i in range (0,8):
        for j in range (0,8):
            t = g[i,j]*inter5[i,j]
            sig = sig + t
    o5 = sig*inter5        
    E2 = E2 + o5
print("\n\t\tError matrix (Method-2)\n\n",E2)


		Error matrix (Method-2)

 [[  0.008   1.705   0.676  -0.906  -1.106   0.033  -2.026   0.471]
 [  0.036   8.14    3.228  -4.327  -5.281   0.158  -9.67    2.248]
 [ -0.045 -10.152  -4.026   5.396   6.586  -0.197  12.06   -2.804]
 [ -0.039  -8.897  -3.528   4.729   5.772  -0.173  10.569  -2.457]
 [ -0.05  -11.158  -4.425   5.931   7.239  -0.216  13.255  -3.082]
 [  0.031   7.041   2.792  -3.742  -4.568   0.137  -8.364   1.945]
 [  0.052  11.793   4.677  -6.269  -7.651   0.229 -14.009   3.257]
 [  0.031   6.882   2.729  -3.658  -4.465   0.134  -8.175   1.901]]


In [21]:
# Square of norm of a matrix i.e || g - g_hat ||^2

su1 = 0
for i in range (r,rank):
    su1 = su1 + ((sigma2[i])**2)
print("\nSquare of norm of a matrix i.e || g - g_hat ||^2\n",su1)


Square of norm of a matrix i.e || g - g_hat ||^2
 2048.9984249642494


In [22]:
su2 = 0
for i in range (0,r):
    su2 = su2 + ((sigma2[i])**2)
print("\nSum of square of the first k singular values:\n",su2)


Sum of square of the first k singular values:
 1607643.0015750367
